In [1]:
#NumPY

#numpy is a python library used to deal with an array

#It also has functions for working in domain of algebra, fourier transform and matrices
#NumPy stands for Numerical Python

In [2]:
import numpy as np

In [3]:
#array() --> used to create 1d or 2d array
arr = np.array([10,20,30,40,50])
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [4]:
#NumPy vs List
list1 = [10,20,30,40,50]
print(list1)

#multiplication each element by 2
print(list1*2)

for i in list1:
    print(i*2)

[10, 20, 30, 40, 50]
[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
20
40
60
80
100


In [5]:
arr = np.array([10,20,30,40,50])
print(arr*2)

[ 20  40  60  80 100]


In [6]:
#array is a collection of similar date type
arr = np.array([20,40,'python','time'])
print(arr)

['20' '40' 'python' 'time']


In [7]:
#shape property
#used to determine the dimensions of an array (1d,2d,3d)

#for 1d array shape returns (n,)
#where n is the number of elements

#for 2d array shape returns (n,m)
#where m is the number of columns and n is the number of rows

print(arr.shape)

(4,)


In [8]:
#indexing and slicing
arr= np.array([10,20,30,40,50,60])

print(arr[3])
print(arr[0:4])
print(arr[1:-1])

40
[10 20 30 40]
[20 30 40 50]


In [9]:
#2D Array
twod = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(twod)
print(twod.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [10]:
#indexing in 2d array
twod = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(twod)
print(twod[2,1])
 
#print the second row
print(twod[1,:])
#print the third column
print(twod[:,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
8
[4 5 6]
[3 6 9]


In [16]:
#creating array from scratch with only values zeros 
arr1=np.zeros((2,3),dtype=int)
print(arr1,arr1.shape)

#creating array from scratch with only values ones
arr2=np.ones((2,2),dtype=int)
print(arr2,arr1.shape)

#creating array from scratch with only value 100
arr2=np.full((2,2),100)
print(arr2,arr1.shape)

#creating array from scratch as identity matrix
arr2=np.eye(3)
print(arr2,arr1.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1]
 [1 1]] (2, 3)
[[100 100]
 [100 100]] (2, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (2, 3)


In [11]:
#dtype property
#used to determine the data type of an array

arr = np.array([10,20,30,40,50])
print(arr.dtype)
print(arr.itemsize,'Bytes')  #it will return memory size of one array element

#int32 : memory size of one array elements in BITS [4 bytes]    8BITS --> 1 BYTE
#int64 : memory size of one array elements in BYTES [8 bytes]

arr = np.array([10,20,30,40,50],dtype='i2')
print(arr.itemsize,'Bytes')     #2bytes --> 16 digit

arr = np.array([10,20,30,40,50],dtype='i1')
print(arr.itemsize,'Bytes')     #1bytes --> 8 digit

int64
8 Bytes
2 Bytes
1 Bytes


In [12]:
# copy() vs view()

#in copy() if you make any changes in org array , it won't effect the copied array
#if you make any changes in copied array , it won't effect the org array 

org_arr = np.array([10,20,30,40])
print(org_arr)

copied_arr = org_arr.copy()
print(copied_arr)

copied_arr[0]=100
print(copied_arr)
print(org_arr)

[10 20 30 40]
[10 20 30 40]
[100  20  30  40]
[10 20 30 40]


In [13]:
#view()

#in view() if you make any changes in org array , it would effect the copied array
#if you make any changes in copied array , it will effect the org array 

org_arr = np.array([10,20,30,40])
print(org_arr)

copied_arr = org_arr.view()
print(copied_arr)

copied_arr[0]=100
print(copied_arr)
print(org_arr)

[10 20 30 40]
[10 20 30 40]
[100  20  30  40]
[100  20  30  40]


In [14]:
#reshape() : used to change the dimensions of an array

# convert 1D into 2D

#1d --> 2d    2d --> 1d

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.shape)   #12 --> 2X6 6X2 3X4 4X3 12X1 1X12

arr = arr.reshape(3,4)
print(arr)

(12,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
# convert 2D into 1D

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)

arr = arr.reshape(9)
print(arr)

(3, 3)
[1 2 3 4 5 6 7 8 9]


In [16]:
# another way to convert 2D into 1D

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
#arr = arr.reshape(-1)
arr=arr.flatten()
print(arr)

[1 2 3 4 5 6 7 8 9]


In [17]:
#Filter an array
arr = np.array([23,7,3,6,2,54,1,67])
op = arr%2==0
print(op)           #BOOLEAN MASKING 
print(arr[op])

[False False False  True  True  True False False]
[ 6  2 54]


In [18]:
arr = np.array([4,7,3,6,2,5,4,1,8,9,5,3,2])
res = arr > 5
print(arr[res])

[7 6 8 9]


In [19]:
arr = np.array([23,4,5,7,9,1,254,89,67])
res = (arr>2) & (arr<27)
print(arr[res])

[23  4  5  7  9]


In [20]:
#Modify element using boolean indexing
arr = np.array([12,3,4,5,32,67,52,25,50])
arr[arr%2==0] = 0
print(arr)

[ 0  3  0  5  0 67  0 25  0]


In [21]:
#where() --> used to return index numbers is an output
arr = np.array([1,4,2,7,8,3,9,10,2,4])
res = np.where(arr>5)
print(res)
print(arr[res])

(array([3, 4, 6, 7]),)
[ 7  8  9 10]


In [22]:
# concatenate()
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8,9])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6 7 8 9]


In [23]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[5,6,7],[11,8,9],[14,15,16]])
arr = np.concatenate((arr1,arr2))
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 5  6  7]
 [11  8  9]
 [14 15 16]]


In [24]:
# split(arrayname,splitvalue)
arr = np.array([1,2,3,4,5,6,7,8])
arr = np.array_split(arr,3)
print(arr)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [25]:
# sorting on an array 
#sort()

arr = np.array([1,4,2,7,9,3,5,8,6,10])
print(np.sort(arr))     # by default it will sort in ascending order

[ 1  2  3  4  5  6  7  8  9 10]


In [26]:
arr = np.array([1,4,2,7,9,3,5,8,6,10])
print(np.sort(arr)[::-1])    #descending order

[10  9  8  7  6  5  4  3  2  1]


In [27]:
# zeros()  ones()    full()   sum() 

#zeros() it is usd fill an array filled with 0's

#1d
arr =  np.zeros(6)
print(arr)


[0. 0. 0. 0. 0. 0.]


In [28]:
arr =  np.zeros(6,dtype='i')
print(arr)

[0 0 0 0 0 0]


In [29]:
arr =  np.zeros((3,3),dtype='i')
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [30]:
#ones() it is usd fill an array filled with 1's
#default data type will be float

arr = np.ones(6)
print(arr)

[1. 1. 1. 1. 1. 1.]


In [31]:
#full(size,constantValue)
#used to fill an array filled with constant value

x = np.full((3,4),26)
print(x)

[[26 26 26 26]
 [26 26 26 26]
 [26 26 26 26]]


In [32]:
#sum()
print(x.sum())

312


In [33]:
#Numpy Random Module
from numpy import random
x = random.randint(100)
print(x)

31


In [34]:
x = random.randint(120,200)
print(x)

123


In [ ]:
#rand method to generate a random float value btwn 0 and 1
x = random.rand()
print(x)

In [35]:
#1D array
x = random.randint(100,size=(7))
print(x)

[90 92 38 34 41 52 21]


In [44]:
#2D array
x = random.randint(20,40,size=(5,3))
print(x)

print(x.sum())

[[39 27 35]
 [39 31 32]
 [28 25 24]
 [33 27 29]
 [35 32 28]]
464


In [45]:
#1D array
x = random.rand(20)
print(x)

[0.99009934 0.57975852 0.86220805 0.62902622 0.7857872  0.80743024
 0.9453093  0.08367228 0.49662461 0.95076056 0.93783326 0.32750861
 0.24124011 0.92717432 0.51050179 0.33637655 0.82170522 0.52559572
 0.4912486  0.76252141]


In [47]:
#2D array
x = random.rand(5,6)
print(x)

[[0.26549355 0.11455528 0.5193274  0.80992504 0.27191477 0.76895627]
 [0.78745596 0.62972035 0.74904623 0.52778827 0.1407177  0.69938834]
 [0.62497883 0.61709712 0.41128614 0.28069758 0.19877513 0.97494095]
 [0.92683503 0.13413883 0.54835162 0.06984213 0.08771745 0.1504809 ]
 [0.39126775 0.46618602 0.88980629 0.98743569 0.28414835 0.17938201]]


In [48]:
#numpy arange()
#it is usd to generate a sequence of integer value

#arange(x)
#it is used to generate a sequence of integer values starting from zero till x-1
print(np.arange(11))

#arange(x,y)
#it is used to generate a sequence of integer values starting values till y-1
print(np.arange(20,40))

#arange(x,y,stepcount)
#it is used to generate a sequence of values starting from x till y-1
print(np.arange(20,40,2))

[ 0  1  2  3  4  5  6  7  8  9 10]
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[20 22 24 26 28 30 32 34 36 38]


In [50]:
#Numpy Broadcasting
#we can operate arithmetic operations 
#two cases
#both the array should be of same size
#or other array should have only one element
arr1 = np.array([3,4,5])
arr2 = np.array([6,7,8])
print(arr1+arr2)

[ 9 11 13]


In [17]:
arr1 = np.array([3,4,5])
arr2 = np.array([6,7,9])
print(arr1-arr2)

[-3 -3 -4]


In [18]:
arr1 = np.array([3,4,5])
arr2 = np.array([6])
print(arr1*arr2)

[18 24 30]


In [20]:
#Vectorization
#means we can directly perform any operation on the ndarray
#while using python list we need to use loop and traverse it
#but in ndarray we can directly access the whole array at the same time

arr = np.array([1,3,4,5,6])
print(arr.shape)
print(arr*2)
print(arr+7)

(5,)
[ 2  6  8 10 12]
[ 8 10 11 12 13]


In [25]:
#Mathematical Functions
#Aggregate - max,min,mean,median,std,max,min,sum,prod
#power - pow(a.b),sqrt
#rounding - ceil,round,floor
#extra,abs,unique,sort

arr = np.array([12,2,34,5,7,88,95])
print(sum(arr))
print(np.sqrt(arr))
print(np.sort(arr))
print(abs(arr))
print(max(arr))
print(np.median(arr))
print(np.std(arr))

243
[3.46410162 1.41421356 5.83095189 2.23606798 2.64575131 9.38083152
 9.74679434]
[ 2  5  7 12 34 88 95]
[12  2 34  5  7 88 95]
95
12.0
37.24710644836066
